//! MCP protocol foundations. Transport/process authority belongs to the caller.
mod authority;
mod connection;
mod discovery;
mod elicitation;
mod launch;
mod owned;
mod required;
mod roots;
mod sampler;
mod sampling;
mod stdio;
mod values;
pub use authority::{ServerSelection, authorize_server, inspect_server};
pub use connection::{ConnectionError, StderrCapture, StdioConnection};
pub use discovery::{DiscoveredTool, exposed_tool_name};
pub use elicitation::ElicitationContext;
pub use launch::{LocalLaunchError, LocalLauncher, LocalServer};
pub use owned::{McpLocationPin, OwnedLocalServer};
pub use roots::McpRoots;
pub use sampling::SamplingRequest;
pub use stdio::{IdleUpdate, McpError, StdioClient};
pub use values::{decision, render_arguments};
pub(crate) const LIMIT: usize = 1024 * 1024;
pub(crate) mod pool;
