#!/usr/bin/env python3
"""Generate the TypeScript SDK sources from the server's OpenAPI document.

Reads `sdk/openapi.json` and writes:

  * `sdk/typescript/src/generated/types.ts`: one TypeScript type per component schema
  * `sdk/typescript/src/generated/operations.ts`: the operation table, its types, the
    method groups bound to a `Caller`, and `isXxxError` guards per known error tag

WebSocket operations (`x-websocket: true`) are skipped: they are not HTTP methods.
Output is deterministic (types and operations sorted by name), so running the script
twice produces no diff. Usage: `python3 scripts/generate_sdk.py [--check]`; `--check`
exits 1 naming the files that would change.
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SPEC = ROOT / "sdk" / "openapi.json"
OUT = ROOT / "sdk" / "typescript" / "src" / "generated"

BANNER = "// Code generated by scripts/generate_sdk.py from sdk/openapi.json; DO NOT EDIT.\n"
REF_PREFIX = "#/components/schemas/"
LOCATION_QUERY = "location[directory]"
LOCATION_HEADER = "x-cyber-directory"
IDENT = re.compile(r"^[A-Za-z_$][A-Za-z0-9_$]*$")

ERROR_TAGS = [
    "CommandNotFoundError",
    "ConflictError",
    "ForbiddenError",
    "InvalidCursorError",
    "InvalidRequestError",
    "MessageNotFoundError",
    "MemoryNotFoundError",
    "RequestNotFoundError",
    "RewindConflictError",
    "ServiceUnavailableError",
    "BudgetExceededError",
    "SessionBusyError",
    "SessionNotFoundError",
    "UnauthorizedError",
    "UnknownError",
]

# --------------------------------------------------------------------------- schemas


def ref_name(ref: str) -> str:
    if not ref.startswith(REF_PREFIX):
        raise ValueError(f"unsupported $ref {ref}")
    return ref[len(REF_PREFIX):]


def literal(value: object) -> str:
    return json.dumps(value)


def doc(text: str | None, indent: str) -> str:
    if not text:
        return ""
    lines = text.replace("*/", "*\\/").strip().splitlines()
    if len(lines) == 1:
        return f"{indent}/** {lines[0]} */\n"
    body = "".join(f"{indent} *{' ' + line if line else ''}\n" for line in lines)
    return f"{indent}/**\n{body}{indent} */\n"


def compound(ts: str) -> bool:
    """Whether a type has a top-level `|` or `&` (outside brackets and string literals)."""
    depth, quoted = 0, False
    for i, ch in enumerate(ts):
        if ch == '"' and (i == 0 or ts[i - 1] != "\\"):
            quoted = not quoted
        elif not quoted and ch in "{(<[":
            depth += 1
        elif not quoted and ch in "})>]":
            depth -= 1
        elif not quoted and depth == 0 and ch in "|&":
            return True
    return False


def wrap(ts: str) -> str:
    """Parenthesize a union or intersection before combining it further."""
    return f"({ts})" if compound(ts) else ts


def union(members: list[str]) -> str:
    unique = list(dict.fromkeys(members))
    if "unknown" in unique:
        return "unknown"
    return " | ".join(wrap(m) if "&" in m and compound(m) else m for m in unique)


def array(items: str) -> str:
    return f"{items}[]" if IDENT.match(items) else f"Array<{items}>"


def obj(schema: dict, indent: str) -> str:
    props = schema.get("properties", {})
    required = set(schema.get("required", []))
    inner = indent + "  "
    lines = []
    for name, prop in props.items():
        key = name if IDENT.match(name) else literal(name)
        optional = "" if name in required else "?"
        description = prop.get("description") if isinstance(prop, dict) else None
        lines.append(f"{doc(description, inner)}{inner}{key}{optional}: {ts_type(prop, inner)};\n")
    extra = schema.get("additionalProperties")
    if extra not in (None, False):
        value = "unknown" if extra is True else ts_type(extra, inner)
        lines.append(f"{inner}[key: string]: {value};\n")
    if not lines:
        return "Record<string, never>" if extra is False else "Record<string, unknown>"
    return "{\n" + "".join(lines) + indent + "}"


def primitive(kind: str, schema: dict, indent: str) -> str | None:
    if kind == "object":
        has_shape = "properties" in schema or "additionalProperties" in schema
        composite = any(k in schema for k in ("$ref", "oneOf", "anyOf", "allOf"))
        return obj(schema, indent) if has_shape or not composite else None
    if kind == "array":
        return array(ts_type(schema.get("items", True), indent))
    return {"string": "string", "integer": "number", "number": "number", "boolean": "boolean", "null": "null"}[kind]


def own_type(schema: dict, indent: str) -> str | None:
    """The type a schema declares itself, ignoring `$ref` and combinators."""
    if "const" in schema:
        return literal(schema["const"])
    if "enum" in schema:
        return union([literal(v) for v in schema["enum"]])
    kinds = schema.get("type")
    if kinds is None:
        return obj(schema, indent) if "properties" in schema else None
    kinds = kinds if isinstance(kinds, list) else [kinds]
    members = [t for t in (primitive(k, schema, indent) for k in kinds) if t is not None]
    return union(members) if members else None


def ts_type(schema: object, indent: str = "") -> str:
    if schema is True or schema == {}:
        return "unknown"
    if schema is False:
        return "never"
    assert isinstance(schema, dict)
    pieces = []
    if "$ref" in schema:
        pieces.append(ref_name(schema["$ref"]))
    own = own_type(schema, indent)
    if own is not None:
        pieces.append(own)
    for key in ("oneOf", "anyOf"):
        if key in schema:
            pieces.append(union([ts_type(s, indent) for s in schema[key]]))
    pieces.extend(ts_type(s, indent) for s in schema.get("allOf", []))
    if not pieces:
        return "unknown"
    return pieces[0] if len(pieces) == 1 else " & ".join(wrap(p) for p in pieces)


def render_types(schemas: dict) -> str:
    out = [BANNER, "/* eslint-disable */\n"]
    for name in sorted(schemas):
        schema = schemas[name]
        description = schema.get("description") if isinstance(schema, dict) else None
        out.append(f"\n{doc(description, '')}export type {name} = {ts_type(schema)};\n")
    return "".join(out)


# --------------------------------------------------------------------------- operations


def resolve(schemas: dict, schema: dict | None) -> dict | None:
    while isinstance(schema, dict) and "$ref" in schema and len(schema) == 1:
        schema = schemas[ref_name(schema["$ref"])]
    return schema


def success(op: dict) -> tuple[int, dict]:
    code = min(int(c) for c in op["responses"] if c.isdigit() and c.startswith("2"))
    return code, op["responses"][str(code)]


def json_schema(content: dict | None) -> dict | None:
    return (content or {}).get("application/json", {}).get("schema")


def response_shape(schemas: dict, op: dict) -> tuple[str, bool, bool]:
    """(TypeScript result type, unwrap `{ data }`, is a stream)."""
    code, response = success(op)
    content = response.get("content", {})
    if "text/event-stream" in content:
        return "EventEnvelope", False, True
    schema = json_schema(content)
    if schema is None:
        return ("void" if code in (202, 204) else "unknown"), False, False
    target = resolve(schemas, schema) or {}
    if set(target.get("properties", {})) == {"data"} and "data" in target.get("required", []):
        return ts_type(target["properties"]["data"], "    "), True, False
    return ts_type(schema, "    "), False, False


def collect(spec: dict) -> list[dict]:
    schemas = spec["components"]["schemas"]
    ops = []
    for path, methods in spec["paths"].items():
        for method, op in methods.items():
            if op.get("x-websocket"):
                continue  # JSON-RPC over WebSocket, not a typed HTTP method
            params = op.get("parameters", [])
            body = op.get("requestBody")
            result, unwrap, stream = response_shape(schemas, op)
            _, tag, name = op["operationId"].split(".")
            ops.append({
                "id": op["operationId"],
                "tag": tag,
                "name": name,
                "summary": op.get("summary", ""),
                "method": method.upper(),
                "path": path,
                "path_params": re.findall(r"\{(\w+)\}", path),
                "query": [p["name"] for p in params if p["in"] == "query" and p["name"] != LOCATION_QUERY],
                "located": any(p["in"] == "header" and p["name"] == LOCATION_HEADER for p in params),
                "body": None if body is None else ts_type(json_schema(body["content"]), "    "),
                "body_required": bool(body and body.get("required")),
                "result": result,
                "unwrap": unwrap,
                "stream": stream,
            })
    return sorted(ops, key=lambda o: o["id"])


def qualify(ts: str, names: set[str]) -> str:
    """Prefix component type names with the `S.` namespace import."""
    return re.sub(r"(?<![\w.\"])([A-Z]\w*)\b(?![\"\w])", lambda m: f"S.{m[1]}" if m[1] in names else m[1], ts)


def query_type(op: dict) -> str:
    if not op["query"]:
        return "Record<string, never>"
    fields = "".join(f"      {n if IDENT.match(n) else literal(n)}?: QueryValue;\n" for n in op["query"])
    return "{\n" + fields + "    }"


def path_type(op: dict) -> str:
    if not op["path_params"]:
        return "Record<string, never>"
    return "{ " + "; ".join(f"{p}: string" for p in op["path_params"]) + " }"


def render_table(ops: list[dict]) -> str:
    rows = []
    for op in ops:
        body = "none" if op["body"] is None else ("required" if op["body_required"] else "optional")
        rows.append(
            f"  {literal(op['id'])}: {{\n"
            f"    tag: {literal(op['tag'])},\n"
            f"    name: {literal(op['name'])},\n"
            f"    method: {literal(op['method'])},\n"
            f"    path: {literal(op['path'])},\n"
            f"    pathParams: {json.dumps(op['path_params'])},\n"
            f"    query: {json.dumps(op['query'])},\n"
            f"    body: {literal(body)},\n"
            f"    located: {json.dumps(op['located'])},\n"
            f"    unwrap: {json.dumps(op['unwrap'])},\n"
            f"    stream: {json.dumps(op['stream'])},\n"
            f"  }},\n"
        )
    return "export const operations = {\n" + "".join(rows) + "} as const satisfies Record<string, OperationSpec>;\n"


def render_interface(ops: list[dict], names: set[str]) -> str:
    rows = []
    for op in ops:
        body = "undefined" if op["body"] is None else qualify(op["body"], names)
        rows.append(
            f"  {literal(op['id'])}: {{\n"
            f"    path: {path_type(op)};\n"
            f"    query: {query_type(op)};\n"
            f"    body: {body};\n"
            f"    response: {qualify(op['result'], names)};\n"
            f"  }};\n"
        )
    return "export interface Operations {\n" + "".join(rows) + "}\n"


def method_params(op: dict) -> tuple[list[str], str]:
    """The method's parameter list and the `CallParams` literal it forwards."""
    params = [f"{p}: string" for p in op["path_params"]]
    forwarded = []
    if op["path_params"]:
        forwarded.append("path: { " + ", ".join(op["path_params"]) + " }")
    ref = f"Operations[{literal(op['id'])}]"
    if op["body"] is not None:
        params.append(f"body{'' if op['body_required'] else '?'}: {ref}[\"body\"]")
        forwarded.append("body")
    elif op["query"]:
        params.append(f"query?: {ref}[\"query\"]")
        forwarded.append("query")
    params.append(f"options?: {'StreamOptions' if op['stream'] else 'RequestOptions'}")
    return params, "{ " + ", ".join(forwarded) + " }" if forwarded else "{}"


def render_method(op: dict) -> str:
    params, forwarded = method_params(op)
    ref = f"Operations[{literal(op['id'])}]"
    if op["stream"]:
        returns, call = "AsyncIterableIterator<S.EventEnvelope>", "stream"
    else:
        returns, call = f"Promise<{ref}[\"response\"]>", "call"
    summary = f"{op['summary']} (`{op['method']} {op['path']}`)"
    return (
        f"{doc(summary, '      ')}"
        f"      {op['name']}: ({', '.join(params)}): {returns} =>\n"
        f"        caller.{call}({literal(op['id'])}, {forwarded}, options),\n"
    )


def render_groups(ops: list[dict]) -> str:
    tags = sorted({op["tag"] for op in ops})
    out = ["/** Typed methods grouped by OpenAPI tag, bound to a `Caller`. */\n",
           "export function createGroups(caller: Caller) {\n  return {\n"]
    for tag in tags:
        out.append(f"    {tag}: {{\n")
        out.extend(render_method(op) for op in ops if op["tag"] == tag)
        out.append("    },\n")
    out.append("  };\n}\n\nexport type Groups = ReturnType<typeof createGroups>;\n")
    return "".join(out)


def render_guards() -> str:
    out = [
        "export const errorTags = [\n",
        *(f"  {literal(t)},\n" for t in ERROR_TAGS),
        "] as const;\n\n",
        "export type ErrorTag = (typeof errorTags)[number];\n\n",
        "/** An error carrying a server `_tag`, such as `CyberApiError`. */\n",
        "export interface TaggedError<Tag extends string = string> {\n",
        "  readonly tag: Tag;\n  readonly status: number;\n  readonly body: S.ErrorBody;\n}\n\n",
        "function hasTag(err: unknown, tag: string): boolean {\n",
        "  return typeof err === \"object\" && err !== null && (err as { tag?: unknown }).tag === tag;\n}\n",
    ]
    for tag in ERROR_TAGS:
        out.append(
            f"\nexport function is{tag}(err: unknown): err is TaggedError<{literal(tag)}> {{\n"
            f"  return hasTag(err, {literal(tag)});\n}}\n"
        )
    return "".join(out)


PRELUDE = '''import type * as S from "./types.js";

export type HttpMethod = "GET" | "POST" | "PATCH" | "PUT" | "DELETE";
export type QueryValue = string | number | boolean;

export interface OperationSpec {
  readonly tag: string;
  readonly name: string;
  readonly method: HttpMethod;
  readonly path: string;
  readonly pathParams: readonly string[];
  readonly query: readonly string[];
  /** Whether the route takes a JSON body. */
  readonly body: "none" | "optional" | "required";
  /** Location-scoped: the client's directory is sent as `x-cyber-directory`. */
  readonly located: boolean;
  /** The response is a `{ data }` envelope that methods unwrap. */
  readonly unwrap: boolean;
  /** The response is a `text/event-stream` of `EventEnvelope`s. */
  readonly stream: boolean;
}

export interface RequestOptions {
  /** Reuse a key across calls; mutating calls generate a UUIDv7 key otherwise. */
  idempotencyKey?: string;
  signal?: AbortSignal;
  headers?: Record<string, string>;
}

export interface StreamOptions {
  signal?: AbortSignal;
}

export interface CallParams {
  path?: Record<string, string>;
  query?: Record<string, QueryValue | undefined>;
  body?: unknown;
}

/** What generated methods call; implemented by the client runtime. */
export interface Caller {
  call<K extends OperationId>(id: K, params: CallParams, options?: RequestOptions): Promise<Operations[K]["response"]>;
  stream(id: StreamOperationId, params: CallParams, options?: StreamOptions): AsyncIterableIterator<S.EventEnvelope>;
}

export type OperationId = keyof Operations;
export type StreamOperationId = {
  [K in OperationId]: (typeof operations)[K]["stream"] extends true ? K : never;
}[OperationId];
'''


def render_operations(ops: list[dict], names: set[str]) -> str:
    return "\n".join([
        BANNER + "/* eslint-disable */\n" + PRELUDE,
        render_interface(ops, names),
        render_table(ops),
        render_groups(ops),
        render_guards(),
    ])


# --------------------------------------------------------------------------- main


def main() -> int:
    check = "--check" in sys.argv[1:]
    spec = json.loads(SPEC.read_text())
    schemas = spec["components"]["schemas"]
    files = {
        OUT / "types.ts": render_types(schemas),
        OUT / "operations.ts": render_operations(collect(spec), set(schemas)),
    }
    changed = [p for p, text in files.items() if not p.exists() or p.read_text() != text]
    if check:
        for p in changed:
            print(f"out of date: {p.relative_to(ROOT)}", file=sys.stderr)
        return 1 if changed else 0
    OUT.mkdir(parents=True, exist_ok=True)
    for path in changed:
        path.write_text(files[path])
        print(f"wrote {path.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
